// <auto-generated />
using System;
using Finance_it.API.Data.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance_it.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118221402_Creation")]
    partial class Creation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finance_it.API.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Income",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expense",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salary",
                            ParentCategoryId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Debt",
                            ParentCategoryId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Interest",
                            ParentCategoryId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pension",
                            ParentCategoryId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            ExpenseType = 3,
                            Name = "Housing",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            ExpenseType = 1,
                            Name = "Home Rent",
                            ParentCategoryId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            ExpenseType = 1,
                            Name = "Mortgage",
                            ParentCategoryId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            ExpenseType = 2,
                            Name = "Utilities",
                            ParentCategoryId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            ExpenseType = 2,
                            Name = "Internet&Telephone",
                            ParentCategoryId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            ExpenseType = 2,
                            Name = "Home Insurance",
                            ParentCategoryId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            ExpenseType = 2,
                            Name = "Home Maintenance",
                            ParentCategoryId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            ExpenseType = 3,
                            Name = "Transport",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            ExpenseType = 1,
                            Name = "Car Loan",
                            ParentCategoryId = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            ExpenseType = 2,
                            Name = "Fuel",
                            ParentCategoryId = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            ExpenseType = 2,
                            Name = "Public Transport",
                            ParentCategoryId = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            ExpenseType = 2,
                            Name = "Car Insurance",
                            ParentCategoryId = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            ExpenseType = 2,
                            Name = "Car Maintenance",
                            ParentCategoryId = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            ExpenseType = 2,
                            Name = "Parking",
                            ParentCategoryId = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            ExpenseType = 3,
                            Name = "Food",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            ExpenseType = 2,
                            Name = "Groceries",
                            ParentCategoryId = 21,
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            ExpenseType = 2,
                            Name = "Restaurant&Cafés",
                            ParentCategoryId = 21,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            ExpenseType = 3,
                            Name = "Healthcare",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            ExpenseType = 1,
                            Name = "Health Insurance",
                            ParentCategoryId = 24,
                            Type = 2
                        },
                        new
                        {
                            Id = 26,
                            ExpenseType = 2,
                            Name = "Medical Bills",
                            ParentCategoryId = 24,
                            Type = 2
                        },
                        new
                        {
                            Id = 27,
                            ExpenseType = 2,
                            Name = "Medications",
                            ParentCategoryId = 24,
                            Type = 2
                        },
                        new
                        {
                            Id = 28,
                            ExpenseType = 3,
                            Name = "Education",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 29,
                            ExpenseType = 1,
                            Name = "Tuition Fees",
                            ParentCategoryId = 28,
                            Type = 2
                        },
                        new
                        {
                            Id = 30,
                            ExpenseType = 2,
                            Name = "Books&Supplies",
                            ParentCategoryId = 28,
                            Type = 2
                        },
                        new
                        {
                            Id = 31,
                            ExpenseType = 2,
                            Name = "Courses&Trainings",
                            ParentCategoryId = 28,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            ExpenseType = 3,
                            Name = "Entertainment",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 33,
                            ExpenseType = 2,
                            Name = "Subscriptions",
                            ParentCategoryId = 31,
                            Type = 2
                        },
                        new
                        {
                            Id = 34,
                            ExpenseType = 2,
                            Name = "Cinema&Events",
                            ParentCategoryId = 31,
                            Type = 2
                        },
                        new
                        {
                            Id = 35,
                            ExpenseType = 2,
                            Name = "Hobbies",
                            ParentCategoryId = 31,
                            Type = 2
                        },
                        new
                        {
                            Id = 36,
                            ExpenseType = 2,
                            Name = "Travel&Vacation",
                            ParentCategoryId = 31,
                            Type = 2
                        },
                        new
                        {
                            Id = 37,
                            ExpenseType = 3,
                            Name = "Insurance",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 38,
                            ExpenseType = 1,
                            Name = "Life Insurance",
                            ParentCategoryId = 34,
                            Type = 2
                        },
                        new
                        {
                            Id = 39,
                            ExpenseType = 2,
                            Name = "Other Insurance",
                            ParentCategoryId = 34,
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            ExpenseType = 3,
                            Name = "Family&Children",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 41,
                            ExpenseType = 2,
                            Name = "Childcare",
                            ParentCategoryId = 37,
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            ExpenseType = 1,
                            Name = "School Fees",
                            ParentCategoryId = 37,
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            ExpenseType = 2,
                            Name = "Activities",
                            ParentCategoryId = 37,
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            ExpenseType = 2,
                            Name = "Clothes",
                            ParentCategoryId = 37,
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            ExpenseType = 3,
                            Name = "Other/Miscellaneous",
                            ParentCategoryId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            ExpenseType = 1,
                            Name = "Taxes&Fees",
                            ParentCategoryId = 42,
                            Type = 2
                        },
                        new
                        {
                            Id = 47,
                            ExpenseType = 2,
                            Name = "Unexpected Expenses",
                            ParentCategoryId = 42,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.FinancialEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialEntries");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.MonthlyAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregateName")
                        .HasColumnType("int");

                    b.Property<decimal>("AggregateValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MonthlyAggregates");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Email_Unique")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.WeeklyAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregateName")
                        .HasColumnType("int");

                    b.Property<decimal>("AggregateValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklyAggregates");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.YearlyAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregateName")
                        .HasColumnType("int");

                    b.Property<decimal>("AggregateValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("YearlyAggregates");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.Category", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("ParentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.FinancialEntry", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("FinancialEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.Goal", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.MonthlyAggregate", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("MonthlyAgregates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.Recommendation", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.WeeklyAggregate", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("WeeklyAgregates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.YearlyAggregate", b =>
                {
                    b.HasOne("Finance_it.API.Data.Entities.User", "User")
                        .WithMany("YearlyAgregates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Finance_it.API.Data.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("FinancialEntries");

                    b.Navigation("Goals");

                    b.Navigation("MonthlyAgregates");

                    b.Navigation("Recommendations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("WeeklyAgregates");

                    b.Navigation("YearlyAgregates");
                });
#pragma warning restore 612, 618
        }
    }
}
